#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

transmission_traffic - Plugin to Transmission network traffic

=head1 CONFIGURATION

No configuration

=head1 AUTHOR

Neville Li (neville.lyh@gmail.com)

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

case $1 in
    config)
        cat << 'EOF'
graph_order down up
graph_title Transmission traffic
graph_vlabel KB/s
graph_category transmission
graph_scale no
down.label down
up.label up
EOF
        exit 0
esac

transmission-remote -l | grep "^Sum:" | awk '{print "down.value "$(NF)"\nup.value "$(NF-1)}'
