#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

transmission_traffic - Plugin to Transmission network traffic

=head1 CONFIGURATION

No configuration

=head1 AUTHOR

Neville Li (neville.lyh@gmail.com)

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

case $1 in
    config)
        cat << 'EOF'
graph_order down up
graph_args --base 1000
graph_title Transmission traffic
graph_vlabel bytes per ${graph_period}
graph_category transmission
down.label down
up.label up
EOF
        exit 0
esac

#transmission-remote -l | grep "^Sum:" | awk '{print "down.value "$(NF)"\nup.value "$(NF-1)}'
sum=$(transmission-remote -l | grep "^Sum:")
down=$(echo ${sum} | awk '{print $(NF)"*1000/1"}' | bc)
up=$(echo ${sum} | awk '{print $(NF-1)"*1000/1"}' | bc)
echo "down.value ${down}"
echo "up.value ${up}"
